language: python
env:
   - DJANGO='>=1.8,<1.9'
   - DJANGO='>=1.9,<1.10'
   - DJANGO='>=1.10,<1.11'
   - DJANGO='>=1.11,<1.12'
   - DJANGO='>=2.0,<2.1'
python:
   - "2.7"
   - "3.6"
install:
   - pip install -e .
   - pip install -r requirements/requirements_test.txt
   - pip install "Django${DJANGO}"
before_script:
    flake8 djtriggers/
script:
    pytest -v --capture=sys --cov=djtriggers/ djtriggers/ --cov-report term-missing:skip-covered
after_success:
    coveralls
